"""
chunk_godot.py — Godot RST → cleaned chunks via Qwen3 (remote Ollama)

Directory mapping:
  godot/classes/          → CLASS prompt  → godot_chk/classes/
  godot/getting_started/  → TUTORIAL prompt → godot_chk/getting_started/
  godot/tutorials/        → TUTORIAL prompt → godot_chk/tutorials/

Output files use .chk extension. Each .chk file contains one or more chunks
separated by ---CHUNK--- so you can re-ingest without re-running Qwen.
"""

import re
import sys
import time
from pathlib import Path
import ollama

# ── Ollama remote client ────────────────────────────────────────────────────
OLLAMA_HOST  = "http://192.168.0.36:11434"
OLLAMA_MODEL = "qwen3:14b"          # swap to "qwen3:8b" for speed

client = ollama.Client(host=OLLAMA_HOST)

# ── Directory routing ────────────────────────────────────────────────────────
INPUT_ROOT  = Path("./godot")
OUTPUT_ROOT = Path("./godot_chk")

# Each entry: (glob_pattern_relative_to_INPUT_ROOT, prompt_type)
# prompt_type is either "class" or "tutorial"
PATH_ROUTING = [
    ("classes/**/*.rst",         "class"),
    ("getting_started/**/*.rst", "tutorial"),
    ("tutorials/**/*.rst",       "tutorial"),
]

# ── Prompts ──────────────────────────────────────────────────────────────────
SYSTEM_PROMPT = """You are a documentation pre-processor for a Godot Engine RAG system. Your sole job is to clean and restructure raw RST documentation files into dense, embedding-friendly plain text chunks.

RULES — follow every one exactly:

1. OUTPUT FORMAT: Return only the cleaned chunk. No preamble, no "Here is the cleaned chunk:", no markdown code fences, no explanation after.

2. ALWAYS START with this metadata block (fill in the values):
   Document: [class or tutorial name]
   Path: [original .rst file path]
   Summary: [one sentence describing what this chunk covers]

3. STRIP completely — do not keep, mention, or reference:
   - RST directives starting with ".." (.. code-block::, .. note::, .. warning::, etc.)
   - Substitution definitions: lines like ".. |virtual| replace:: ..."
   - Internal hyperlink syntax: :ref:`SomeClass <class_SomeClass>` → write just "SomeClass"
   - GitHub URLs, "DO NOT EDIT" headers, generator comments, XML source links
   - ASCII table borders: lines made of "+---+" or "|   |" patterns
   - Empty lines used only for RST spacing

4. CONVERT to plain prose/lists:
   - RST tables → bullet list of "name (Type): description. Default: value."
   - ".. note::" blocks → inline sentence starting with "Note:"
   - ".. warning::" blocks → inline sentence starting with "Warning:"
   - Method signatures → "Method: name(params) → ReturnType" then description below

5. KEEP intact:
   - All GDScript and C# code examples (preserve indentation, remove RST fences, use plain labels "GDScript:" and "C#:")
   - All class names, method names, property names (exact casing)
   - Inheritance chain ("inherits from X")
   - Enum values and their integer mappings

6. CHUNK SIZE target: 300–600 words of clean content (excluding the metadata block). If the input is a long tutorial with multiple H2 headers, output ONE chunk per H2 section, each with its own metadata block. Add "Part N of M:" to the Summary line when splitting.

7. BOOLEAN CONTEXT notes and edge cases count as key rules — do not discard them. Rewrite as "Key Rule: [plain sentence]".

Now process the RST content the user provides."""

USER_PROMPT_CLASS = """Process the following Godot RST documentation file. It is a CLASS reference page.

Split it into these chunks in order:
1. Identity & Description chunk (what the class is, inheritance, key rules)
2. Properties chunk (all member variables as bullet list)
3. Methods chunk (group up to 5 related methods per chunk; each gets its own if it has a code example)

Output each chunk separated by the line:
---CHUNK---

RST content:
"""

USER_PROMPT_TUTORIAL = """Process the following Godot RST documentation file. It is a TUTORIAL page.

Split it by H2 headers (lines underlined with "=" or "-" in RST). Each H2 section becomes one chunk. If a section exceeds 600 words, split further at H3 headers.

Keep the tutorial title and the page Path in every chunk's metadata.
Output each chunk separated by the line:
---CHUNK---

RST content:
"""

# ── Pre-filter ────────────────────────────────────────────────────────────────
# Patterns that are pure RST boilerplate — safe to strip before sending to LLM.
_STRIP_PATTERNS = [
    re.compile(r"^\.\.\s*\|.*$"),                   # substitution defs: .. |virtual| replace::
    re.compile(r"^[+|][-=+|]+[+|]\s*$"),            # ASCII table borders: +-----+-----+
    re.compile(r"^:github_url:.*$"),                 # github_url meta
    re.compile(r"^:gitref:.*$"),                     # gitref meta
    re.compile(r".*DO NOT EDIT THIS FILE.*"),        # generator headers
    re.compile(r".*Generated automatically.*"),      # generator comments
    re.compile(r"^\.\. Generated.*$"),               # RST generator line
    re.compile(r"^\.\. XML source.*$"),              # XML source line
]

def pre_filter(text: str) -> str:
    """
    Strip RST boilerplate line-by-line before sending to Qwen.
    Removes ~15-20% of tokens from class reference files.
    """
    lines = text.splitlines()
    kept = []
    for line in lines:
        if any(pat.match(line.strip()) for pat in _STRIP_PATTERNS):
            continue
        kept.append(line)

    # Collapse runs of 3+ blank lines down to 2
    result = []
    blank_count = 0
    for line in kept:
        if line.strip() == "":
            blank_count += 1
            if blank_count <= 2:
                result.append(line)
        else:
            blank_count = 0
            result.append(line)

    return "\n".join(result)

# ── LLM call ─────────────────────────────────────────────────────────────────
def call_qwen(system: str, user: str, retries: int = 3) -> str:
    for attempt in range(1, retries + 1):
        try:
            response = client.chat(
                model=OLLAMA_MODEL,
                messages=[
                    {"role": "system", "content": system},
                    {"role": "user",   "content": user},
                ],
                options={"temperature": 0.1},   # low temp for deterministic cleaning
            )
            return response["message"]["content"]
        except Exception as e:
            print(f"  [!] Ollama error (attempt {attempt}/{retries}): {e}")
            if attempt < retries:
                time.sleep(3 * attempt)
    return ""

# ── Core processor ────────────────────────────────────────────────────────────
def process_file(raw_content: str, prompt_type: str, file_path: Path) -> str:
    """
    1. Pre-filter boilerplate
    2. Send to Qwen with the right user prompt
    3. Return raw model output (chunks separated by ---CHUNK---)
    """
    filtered = pre_filter(raw_content)

    user_prompt = (USER_PROMPT_CLASS if prompt_type == "class" else USER_PROMPT_TUTORIAL)
    user_message = user_prompt + filtered

    print(f"  → pre-filter: {len(raw_content)} chars → {len(filtered)} chars "
          f"({100*(1-len(filtered)/max(len(raw_content),1)):.0f}% stripped)")

    result = call_qwen(SYSTEM_PROMPT, user_message)

    if not result:
        print(f"  [!] Empty response — saving pre-filtered content as fallback.")
        return filtered

    return result

# ── Parse helper (also useful when re-ingesting .chk files) ──────────────────
def parse_chunks(chk_content: str) -> list[str]:
    """Split a .chk file on ---CHUNK--- and return non-empty chunks."""
    parts = chk_content.split("---CHUNK---")
    return [p.strip() for p in parts if p.strip()]

# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    if not INPUT_ROOT.exists():
        print(f"Error: input root '{INPUT_ROOT}' not found.")
        sys.exit(1)

    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)

    # Collect all (file_path, prompt_type) pairs without duplicates
    jobs: list[tuple[Path, str]] = []
    seen: set[Path] = set()

    for pattern, prompt_type in PATH_ROUTING:
        for file_path in sorted(INPUT_ROOT.glob(pattern)):
            if file_path not in seen:
                seen.add(file_path)
                jobs.append((file_path, prompt_type))

    total = len(jobs)
    print(f"Found {total} RST files to process.\n")

    for idx, (file_path, prompt_type) in enumerate(jobs, 1):
        relative_path = file_path.relative_to(INPUT_ROOT)
        output_path   = OUTPUT_ROOT / relative_path.with_suffix(".chk")
        output_path.parent.mkdir(parents=True, exist_ok=True)

        print(f"[{idx}/{total}] {relative_path}  (type={prompt_type})")

        # Skip if already processed (re-run safety)
        if output_path.exists():
            print(f"  → already exists, skipping. Delete to reprocess.")
            continue

        try:
            raw = file_path.read_text(encoding="utf-8")
            processed = process_file(raw, prompt_type, file_path)

            output_path.write_text(processed, encoding="utf-8")

            chunk_count = len(parse_chunks(processed))
            print(f"  ✓ saved {chunk_count} chunk(s) → {output_path}")

        except Exception as e:
            print(f"  [!] Failed: {e}")

    print(f"\nDone. Output in '{OUTPUT_ROOT}/'")

if __name__ == "__main__":
    main()
