"""
chunk_godot.py — Godot RST → cleaned chunks via Qwen3 (remote Ollama)

Uses a thread pool to process multiple files in parallel, saturating the GPU
instead of leaving it idle between sequential token generation calls.

Usage:
    python chunk_godot.py            # default 3 workers
    python chunk_godot.py --workers 5
    python chunk_godot.py --workers 1  # single-threaded (debug)

Directory mapping:
  godot/classes/          → CLASS prompt  → godot_chk/classes/
  godot/getting_started/  → TUTORIAL prompt → godot_chk/getting_started/
  godot/tutorials/        → TUTORIAL prompt → godot_chk/tutorials/
"""

import re
import sys
import time
import argparse
import threading
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed
import ollama

# ── Config ────────────────────────────────────────────────────────────────────
OLLAMA_HOST       = "http://192.168.0.36:11434"
OLLAMA_MODEL      = "qwen3:14b"
MAX_SECTION_CHARS = 3000   # max chars per LLM call — aligned with num_ctx=3072
DEFAULT_WORKERS   = 3      # parallel files; raise to 4-5 if GPU stays under 80%

# Each worker gets its own client (thread-safe, no shared state)
_local = threading.local()

def get_client() -> ollama.Client:
    if not hasattr(_local, "client"):
        _local.client = ollama.Client(host=OLLAMA_HOST)
    return _local.client

# ── Directory routing ─────────────────────────────────────────────────────────
INPUT_ROOT  = Path("./godot")
OUTPUT_ROOT = Path("./godot_chk")

PATH_ROUTING = [
    ("classes/**/*.rst",         "class"),
    ("getting_started/**/*.rst", "tutorial"),
    ("tutorials/**/*.rst",       "tutorial"),
]

# ── Prompts ───────────────────────────────────────────────────────────────────
SYSTEM_PROMPT = """You are a documentation pre-processor for a Godot Engine RAG system. Your sole job is to clean and restructure raw RST documentation sections into dense, embedding-friendly plain text chunks.

RULES — follow every one exactly:

1. OUTPUT FORMAT: Return only the cleaned chunk. No preamble, no "Here is the cleaned chunk:", no markdown code fences, no explanation after. No <answer> tags.

2. ALWAYS START with this metadata block (fill in the values):
   Document: [class or tutorial name]
   Path: [original .rst file path]
   Summary: [one sentence describing what this chunk covers]

3. STRIP completely — do not keep, mention, or reference:
   - RST directives starting with ".." (.. code-block::, .. note::, .. warning::, etc.)
   - Substitution definitions: lines like ".. |virtual| replace:: ..."
   - Internal hyperlink syntax: :ref:`SomeClass <class_SomeClass>` → write just "SomeClass"
   - GitHub URLs, "DO NOT EDIT" headers, generator comments, XML source links
   - ASCII table borders: lines made of "+---+" or "|   |" patterns
   - Empty lines used only for RST spacing

4. CONVERT to plain prose/lists:
   - RST tables → bullet list of "name (Type): description. Default: value."
   - ".. note::" blocks → inline sentence starting with "Note:"
   - ".. warning::" blocks → inline sentence starting with "Warning:"
   - Method signatures → "Method: name(params) → ReturnType" then description below

5. KEEP intact, with plain labels (no markdown fences):
   - All GDScript examples — label as "GDScript:" on its own line, then indented code
   - All C# examples — label as "C#:" on its own line, then indented code
   - All class names, method names, property names (exact casing)
   - Inheritance chain ("inherits from X")
   - Enum values and their integer mappings

6. CHUNK SIZE target: 300–600 words. Very short sections (under 100 words) still need the metadata header — do not skip them.

7. BOOLEAN CONTEXT notes and edge cases count as key rules — rewrite as "Key Rule: [plain sentence]".

8. Do NOT add information not present in the input. Do NOT hallucinate methods, use cases, or best practices. Only clean and reformat what is given.

Output ONLY the cleaned chunk. No separators — the calling script handles those."""

USER_PROMPT_CLASS_DESCRIPTION = "Process this Godot CLASS reference section — class identity, description, inheritance.\nFile path for metadata: {path}\n\nRST content:\n{content}"
USER_PROMPT_CLASS_PROPERTIES  = "Process this Godot CLASS reference section — class properties/member variables.\nFile path for metadata: {path}\n\nRST content:\n{content}"
USER_PROMPT_CLASS_METHODS     = "Process this Godot CLASS reference section — methods (group: {group_label}).\nFile path for metadata: {path}\n\nRST content:\n{content}"
USER_PROMPT_TUTORIAL_SECTION  = "Process this Godot TUTORIAL section (one H2/H3 of a larger tutorial).\nFile path for metadata: {path}\n\nRST content:\n{content}"

# ── Pre-filter ────────────────────────────────────────────────────────────────
_STRIP_PATTERNS = [
    re.compile(r"^\.\.\s*\|.*$"),
    re.compile(r"^[+|][-=+|]+[+|]\s*$"),
    re.compile(r"^:github_url:.*$"),
    re.compile(r"^:gitref:.*$"),
    re.compile(r".*DO NOT EDIT THIS FILE.*"),
    re.compile(r".*Generated automatically.*"),
    re.compile(r"^\.\. Generated.*$"),
    re.compile(r"^\.\. XML source.*$"),
]

def pre_filter(text: str) -> str:
    kept = [l for l in text.splitlines()
            if not any(p.match(l.strip()) for p in _STRIP_PATTERNS)]
    result, blank_count = [], 0
    for line in kept:
        if line.strip() == "":
            blank_count += 1
            if blank_count <= 2:
                result.append(line)
        else:
            blank_count = 0
            result.append(line)
    return "\n".join(result)

# ── RST splitter ──────────────────────────────────────────────────────────────
_HEADING_RE = re.compile(r"^(.+)\n([=\-~^\"'`#*+])\2{2,}\s*$", re.MULTILINE)

def _split_by_headings(text: str) -> list[tuple[str, str]]:
    matches = list(_HEADING_RE.finditer(text))
    if not matches:
        return [("", text)]
    sections = []
    preamble = text[:matches[0].start()].strip()
    if preamble:
        sections.append(("__preamble__", preamble))
    for i, m in enumerate(matches):
        title = m.group(1).strip()
        start = m.end()
        end   = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        body  = text[start:end].strip()
        sections.append((title, body))
    return sections

def split_class_rst(text: str) -> list[tuple[str, str]]:
    sections = _split_by_headings(text)
    result, method_buffer, method_chars, method_group = [], [], 0, 1

    def flush():
        nonlocal method_group, method_buffer, method_chars
        if method_buffer:
            result.append((f"methods_{method_group}", "\n\n".join(method_buffer)))
            method_group += 1
            method_buffer.clear()
            method_chars = 0

    for title, body in sections:
        if not body:
            continue
        label = title.lower()
        chunk = f"{title}\n{body}" if title not in ("__preamble__", "") else body

        if label in ("__preamble__", "description", ""):
            flush(); result.append(("description", chunk))
        elif any(k in label for k in ("propert", "member")):
            flush(); result.append(("properties", chunk))
        elif any(k in label for k in ("method", "constructor", "operator", "signal", "enum", "theme")):
            if method_chars + len(chunk) > MAX_SECTION_CHARS:
                flush()
            method_buffer.append(chunk)
            method_chars += len(chunk)
        else:
            flush(); result.append(("other", chunk))

    flush()
    return result

def split_tutorial_rst(text: str) -> list[tuple[str, str]]:
    result = []
    for title, body in _split_by_headings(text):
        content = f"{title}\n{body}" if title not in ("__preamble__", "") else body
        if len(content) <= MAX_SECTION_CHARS:
            result.append((title, content))
        else:
            paragraphs = re.split(r"\n{2,}", content)
            buf, part = "", 1
            for para in paragraphs:
                if len(buf) + len(para) > MAX_SECTION_CHARS and buf:
                    result.append((f"{title} (part {part})", buf.strip()))
                    part += 1; buf = para
                else:
                    buf += "\n\n" + para
            if buf.strip():
                result.append((f"{title} (part {part})", buf.strip()))
    return result

# ── LLM call ──────────────────────────────────────────────────────────────────
def call_qwen(user_message: str, retries: int = 3) -> str:
    client = get_client()
    for attempt in range(1, retries + 1):
        try:
            response = client.chat(
                model=OLLAMA_MODEL,
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user",   "content": user_message},
                ],
                options={"temperature": 0.1, "num_ctx": 3072},
            )
            return response["message"]["content"].strip()
        except Exception as e:
            if attempt < retries:
                time.sleep(4 * attempt)
            else:
                return ""
    return ""

# ── File processing ───────────────────────────────────────────────────────────
def process_file(raw: str, prompt_type: str, file_path: Path) -> tuple[str, list[str]]:
    """Returns (final_chk_content, log_lines)."""
    path_str = str(file_path)
    filtered = pre_filter(raw)
    logs = [f"  pre-filter: {len(raw)}→{len(filtered)} chars "
            f"({100*(1-len(filtered)/max(len(raw),1)):.0f}% stripped)"]
    chunks = []

    if prompt_type == "class":
        sections = split_class_rst(filtered)
        logs.append(f"  split: {len(sections)} section(s)")
        method_group = 1
        for label, content in sections:
            if not content.strip():
                continue
            if label == "description":
                prompt = USER_PROMPT_CLASS_DESCRIPTION.format(path=path_str, content=content)
            elif label == "properties":
                prompt = USER_PROMPT_CLASS_PROPERTIES.format(path=path_str, content=content)
            elif label.startswith("methods_"):
                prompt = USER_PROMPT_CLASS_METHODS.format(path=path_str, content=content, group_label=f"group {method_group}")
                method_group += 1
            else:
                prompt = USER_PROMPT_TUTORIAL_SECTION.format(path=path_str, content=content)
            result = call_qwen(prompt)
            if result:
                chunks.append(result)
                logs.append(f"  ✓ {label} ({len(content)} chars)")
            else:
                logs.append(f"  ✗ {label} — empty response")
    else:
        sections = split_tutorial_rst(filtered)
        logs.append(f"  split: {len(sections)} section(s)")
        for title, content in sections:
            if not content.strip():
                continue
            prompt = USER_PROMPT_TUTORIAL_SECTION.format(path=path_str, content=content)
            result = call_qwen(prompt)
            short = (title[:35] + "…") if len(title) > 35 else (title or "(preamble)")
            if result:
                chunks.append(result)
                logs.append(f"  ✓ {short!r} ({len(content)} chars)")
            else:
                logs.append(f"  ✗ {short!r} — empty response")

    if not chunks:
        logs.append("  ! no chunks produced — using pre-filtered fallback")
        return filtered, logs

    return "\n---CHUNK---\n".join(chunks), logs

# ── Worker (called from thread pool) ─────────────────────────────────────────
_print_lock = threading.Lock()

def worker(args: tuple) -> tuple[Path, int, bool]:
    """Process one file. Returns (output_path, chunk_count, success)."""
    idx, total, file_path, prompt_type, output_path = args

    with _print_lock:
        print(f"[{idx}/{total}] START  {file_path.relative_to(INPUT_ROOT)}")

    try:
        raw = file_path.read_text(encoding="utf-8")
        content, logs = process_file(raw, prompt_type, file_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content, encoding="utf-8")
        chunk_count = len([p for p in content.split("---CHUNK---") if p.strip()])

        with _print_lock:
            print(f"[{idx}/{total}] DONE   {file_path.name} → {chunk_count} chunk(s)")
            for line in logs:
                print(f"  {line}")

        return output_path, chunk_count, True

    except Exception as e:
        with _print_lock:
            print(f"[{idx}/{total}] FAIL   {file_path.name}: {e}")
        return output_path, 0, False

# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--workers", type=int, default=DEFAULT_WORKERS,
                        help="Parallel files to process (default: %(default)s)")
    args = parser.parse_args()

    if not INPUT_ROOT.exists():
        print(f"Error: '{INPUT_ROOT}' not found.")
        sys.exit(1)

    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)

    # Collect jobs
    jobs, seen = [], set()
    for pattern, prompt_type in PATH_ROUTING:
        for file_path in sorted(INPUT_ROOT.glob(pattern)):
            if file_path in seen:
                continue
            seen.add(file_path)
            relative   = file_path.relative_to(INPUT_ROOT)
            output_path = OUTPUT_ROOT / relative.with_suffix(".chk")
            if output_path.exists():
                print(f"SKIP   {relative} (already processed)")
                continue
            jobs.append((file_path, prompt_type, output_path))

    total = len(jobs)
    print(f"\nProcessing {total} files with {args.workers} worker(s).\n")

    if total == 0:
        print("Nothing to do.")
        return

    work_args = [
        (idx + 1, total, fp, pt, op)
        for idx, (fp, pt, op) in enumerate(jobs)
    ]

    t_start = time.time()
    success, failed = 0, 0

    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        futures = {pool.submit(worker, a): a for a in work_args}
        for future in as_completed(futures):
            _, _, ok = future.result()
            if ok:
                success += 1
            else:
                failed += 1

    elapsed = time.time() - t_start
    print(f"\n{'─'*50}")
    print(f"Done in {elapsed/60:.1f} min — {success} ok, {failed} failed.")
    print(f"Output in '{OUTPUT_ROOT}/'")

if __name__ == "__main__":
    main()
